[com.example.redwood.emojisearch.treehouse.EmojiSearchPresenter]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun launch(): app.cash.redwood.treehouse.ZiplineTreehouseUi
  "sqKEI1vX",

  # val appLifecycle: app.cash.redwood.treehouse.AppLifecycle
  "odhmO/d6",
]

[com.example.redwood.emojisearch.treehouse.HostApi]

functions = [
  # fun close(): kotlin.Unit
  "moYx+T3e",

  # fun openUrl(kotlin.String): kotlin.Unit
  "ARWs/Vu/",

  # suspend fun httpCall(kotlin.String, kotlin.collections.Map<kotlin.String,kotlin.String>): kotlin.String
  "0T9AW1Kn",
]
