import static app.cash.redwood.buildsupport.TargetGroup.ToolkitComposeUi

redwoodBuild {
  targets(ToolkitComposeUi)
  publishing()
}

apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'app.cash.redwood.generator.widget.composeui'

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        api projects.redwoodUiBasicWidget
        api libs.coil.compose
        api libs.jetbrains.compose.material
        implementation projects.redwoodLayoutComposeui
        implementation projects.redwoodLazylayoutComposeui
        implementation projects.redwoodWidgetComposeui
        implementation libs.jetbrains.compose.ui
      }
    }
  }
}

redwoodSchema {
  source = projects.redwoodUiBasicSchema
  type = 'app.cash.redwood.ui.basic.RedwoodUiBasic'
}

android {
  namespace 'app.cash.redwood.ui.basic.composeui'
}
