import static app.cash.redwood.buildsupport.TargetGroup.CommonWithAndroid

apply plugin: 'app.cash.burst'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

redwoodBuild {
  targets(CommonWithAndroid)
}

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        api libs.burst
        api libs.jetbrains.compose.foundation
        api libs.kotlin.test
        api projects.redwoodWidget
        implementation libs.assertk
        implementation libs.burst.coroutines
      }
    }
    androidMain {
      dependencies {
        // This library uses Paparazzi types but consumers must install the Paparazzi plugin.
        compileOnly libs.paparazzi
      }
    }
    jsMain {
      dependencies {
        api projects.redwoodDomTesting
      }
    }

    commonTest {
      dependencies {
        implementation libs.kotlin.test
        implementation libs.assertk
      }
    }
  }
}

android {
  namespace = 'app.cash.redwood.snapshot.testing'
}
