/*
 * Copyright (C) 2023 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package app.cash.redwood.yoga

import app.cash.redwood.yoga.enums.YogaAlign
import app.cash.redwood.yoga.enums.YogaDirection
import app.cash.redwood.yoga.enums.YogaEdge
import app.cash.redwood.yoga.enums.YogaFlexDirection
import app.cash.redwood.yoga.enums.YogaJustify
import app.cash.redwood.yoga.enums.YogaWrap
import kotlin.test.Test
import kotlin.test.assertEquals

class YGAlignItemsTest {
    @Test
    fun test_align_items_stretch() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_items_center() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignItems(YogaAlign.CENTER)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(10f)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(45f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(45f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_items_flex_start() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignItems(YogaAlign.FLEX_START)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(10f)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(90f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_items_flex_end() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignItems(YogaAlign.FLEX_END)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(10f)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(90f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(30f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(30f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(10f)
        root_child1.addChildAt(root_child1_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child_multiline() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(60f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setFlexDirection(YogaFlexDirection.ROW)
        root_child1.setWrap(YogaWrap.WRAP)
        root_child1.setWidth(50f)
        root_child1.setHeight(25f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(25f)
        root_child1_child0.setHeight(20f)
        root_child1.addChildAt(root_child1_child0, 0)
        val root_child1_child1 = createNode(config)
        root_child1_child1.setWidth(25f)
        root_child1_child1.setHeight(10f)
        root_child1.addChildAt(root_child1_child1, 1)
        val root_child1_child2 = createNode(config)
        root_child1_child2.setWidth(25f)
        root_child1_child2.setHeight(20f)
        root_child1.addChildAt(root_child1_child2, 2)
        val root_child1_child3 = createNode(config)
        root_child1_child3.setWidth(25f)
        root_child1_child3.setHeight(10f)
        root_child1.addChildAt(root_child1_child3, 3)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(25f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child3.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child3.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(25f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child1.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child3.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child3.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child3.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child_multiline_override() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(60f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setFlexDirection(YogaFlexDirection.ROW)
        root_child1.setWrap(YogaWrap.WRAP)
        root_child1.setWidth(50f)
        root_child1.setHeight(25f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(25f)
        root_child1_child0.setHeight(20f)
        root_child1.addChildAt(root_child1_child0, 0)
        val root_child1_child1 = createNode(config)
        root_child1_child1.setAlignSelf(YogaAlign.BASELINE)
        root_child1_child1.setWidth(25f)
        root_child1_child1.setHeight(10f)
        root_child1.addChildAt(root_child1_child1, 1)
        val root_child1_child2 = createNode(config)
        root_child1_child2.setWidth(25f)
        root_child1_child2.setHeight(20f)
        root_child1.addChildAt(root_child1_child2, 2)
        val root_child1_child3 = createNode(config)
        root_child1_child3.setAlignSelf(YogaAlign.BASELINE)
        root_child1_child3.setWidth(25f)
        root_child1_child3.setHeight(10f)
        root_child1.addChildAt(root_child1_child3, 3)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(25f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child3.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child3.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(25f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child1.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child3.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child3.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child3.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child_multiline_no_override_on_secondline() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(60f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setFlexDirection(YogaFlexDirection.ROW)
        root_child1.setWrap(YogaWrap.WRAP)
        root_child1.setWidth(50f)
        root_child1.setHeight(25f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(25f)
        root_child1_child0.setHeight(20f)
        root_child1.addChildAt(root_child1_child0, 0)
        val root_child1_child1 = createNode(config)
        root_child1_child1.setWidth(25f)
        root_child1_child1.setHeight(10f)
        root_child1.addChildAt(root_child1_child1, 1)
        val root_child1_child2 = createNode(config)
        root_child1_child2.setWidth(25f)
        root_child1_child2.setHeight(20f)
        root_child1.addChildAt(root_child1_child2, 2)
        val root_child1_child3 = createNode(config)
        root_child1_child3.setAlignSelf(YogaAlign.BASELINE)
        root_child1_child3.setWidth(25f)
        root_child1_child3.setHeight(10f)
        root_child1.addChildAt(root_child1_child3, 3)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(25f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child3.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child3.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(25f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child1.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child1.getLayoutHeight(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child3.getLayoutX(), 0.0f)
        assertEquals(20f, root_child1_child3.getLayoutY(), 0.0f)
        assertEquals(25f, root_child1_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child3.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child_top() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setPosition(YogaEdge.TOP, 10f)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(10f)
        root_child1.addChildAt(root_child1_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(10f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(10f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child_top2() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setPosition(YogaEdge.TOP, 5f)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(10f)
        root_child1.addChildAt(root_child1_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(45f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(45f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_double_nested_child() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setWidth(50f)
        root_child0_child0.setHeight(20f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(15f)
        root_child1.addChildAt(root_child1_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(5f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(15f, root_child1_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(5f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(15f, root_child1_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_column() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child_margin() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setMargin(YogaEdge.LEFT, 5f)
        root_child0.setMargin(YogaEdge.TOP, 5f)
        root_child0.setMargin(YogaEdge.RIGHT, 5f)
        root_child0.setMargin(YogaEdge.BOTTOM, 5f)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setMargin(YogaEdge.LEFT, 1f)
        root_child1_child0.setMargin(YogaEdge.TOP, 1f)
        root_child1_child0.setMargin(YogaEdge.RIGHT, 1f)
        root_child1_child0.setMargin(YogaEdge.BOTTOM, 1f)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(10f)
        root_child1.addChildAt(root_child1_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(5f, root_child0.getLayoutX(), 0.0f)
        assertEquals(5f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(60f, root_child1.getLayoutX(), 0.0f)
        assertEquals(44f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(1f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(1f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(45f, root_child0.getLayoutX(), 0.0f)
        assertEquals(5f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child1.getLayoutX(), 0.0f)
        assertEquals(44f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(-1f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(1f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_child_padding() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setPadding(YogaEdge.LEFT, 5f)
        root.setPadding(YogaEdge.TOP, 5f)
        root.setPadding(YogaEdge.RIGHT, 5f)
        root.setPadding(YogaEdge.BOTTOM, 5f)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setPadding(YogaEdge.LEFT, 5f)
        root_child1.setPadding(YogaEdge.TOP, 5f)
        root_child1.setPadding(YogaEdge.RIGHT, 5f)
        root_child1.setPadding(YogaEdge.BOTTOM, 5f)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(10f)
        root_child1.addChildAt(root_child1_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(5f, root_child0.getLayoutX(), 0.0f)
        assertEquals(5f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(55f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(5f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(5f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(45f, root_child0.getLayoutX(), 0.0f)
        assertEquals(5f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(-5f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(-5f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(5f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_multiline() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(10f)
        root_child1.addChildAt(root_child1_child0, 0)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root_child2.setHeight(20f)
        root.addChildAt(root_child2, 2)
        val root_child2_child0 = createNode(config)
        root_child2_child0.setWidth(50f)
        root_child2_child0.setHeight(10f)
        root_child2.addChildAt(root_child2_child0, 0)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(50f)
        root.addChildAt(root_child3, 3)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(100f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(60f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(100f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(60f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_multiline_column() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(30f)
        root_child1.setHeight(50f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(20f)
        root_child1_child0.setHeight(20f)
        root_child1.addChildAt(root_child1_child0, 0)
        val root_child2 = createNode(config)
        root_child2.setWidth(40f)
        root_child2.setHeight(70f)
        root.addChildAt(root_child2, 2)
        val root_child2_child0 = createNode(config)
        root_child2_child0.setWidth(10f)
        root_child2_child0.setHeight(10f)
        root_child2.addChildAt(root_child2_child0, 0)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(20f)
        root.addChildAt(root_child3, 3)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(30f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(40f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(70f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(70f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(70f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(30f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(40f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(70f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(30f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(70f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_multiline_column2() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(30f)
        root_child1.setHeight(50f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(20f)
        root_child1_child0.setHeight(20f)
        root_child1.addChildAt(root_child1_child0, 0)
        val root_child2 = createNode(config)
        root_child2.setWidth(40f)
        root_child2.setHeight(70f)
        root.addChildAt(root_child2, 2)
        val root_child2_child0 = createNode(config)
        root_child2_child0.setWidth(10f)
        root_child2_child0.setHeight(10f)
        root_child2.addChildAt(root_child2_child0, 0)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(20f)
        root.addChildAt(root_child3, 3)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(30f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(40f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(70f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(70f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(70f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(30f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(40f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(70f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(30f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(70f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_baseline_multiline_row_and_column() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignItems(YogaAlign.BASELINE)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(50f)
        root.addChildAt(root_child1, 1)
        val root_child1_child0 = createNode(config)
        root_child1_child0.setWidth(50f)
        root_child1_child0.setHeight(10f)
        root_child1.addChildAt(root_child1_child0, 0)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root_child2.setHeight(20f)
        root.addChildAt(root_child2, 2)
        val root_child2_child0 = createNode(config)
        root_child2_child0.setWidth(50f)
        root_child2_child0.setHeight(10f)
        root_child2.addChildAt(root_child2_child0, 0)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(20f)
        root.addChildAt(root_child3, 3)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(100f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(90f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(100f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(90f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_items_center_child_with_margin_bigger_than_parent() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setJustifyContent(YogaJustify.CENTER)
        root.setAlignItems(YogaAlign.CENTER)
        root.setWidth(52f)
        root.setHeight(52f)
        val root_child0 = createNode(config)
        root_child0.setAlignItems(YogaAlign.CENTER)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setMargin(YogaEdge.LEFT, 10f)
        root_child0_child0.setMargin(YogaEdge.RIGHT, 10f)
        root_child0_child0.setWidth(52f)
        root_child0_child0.setHeight(52f)
        root_child0.addChildAt(root_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_items_flex_end_child_with_margin_bigger_than_parent() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setJustifyContent(YogaJustify.CENTER)
        root.setAlignItems(YogaAlign.CENTER)
        root.setWidth(52f)
        root.setHeight(52f)
        val root_child0 = createNode(config)
        root_child0.setAlignItems(YogaAlign.FLEX_END)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setMargin(YogaEdge.LEFT, 10f)
        root_child0_child0.setMargin(YogaEdge.RIGHT, 10f)
        root_child0_child0.setWidth(52f)
        root_child0_child0.setHeight(52f)
        root_child0.addChildAt(root_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(52f, root_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_items_center_child_without_margin_bigger_than_parent() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setJustifyContent(YogaJustify.CENTER)
        root.setAlignItems(YogaAlign.CENTER)
        root.setWidth(52f)
        root.setHeight(52f)
        val root_child0 = createNode(config)
        root_child0.setAlignItems(YogaAlign.CENTER)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setWidth(72f)
        root_child0_child0.setHeight(72f)
        root_child0.addChildAt(root_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_items_flex_end_child_without_margin_bigger_than_parent() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setJustifyContent(YogaJustify.CENTER)
        root.setAlignItems(YogaAlign.CENTER)
        root.setWidth(52f)
        root.setHeight(52f)
        val root_child0 = createNode(config)
        root_child0.setAlignItems(YogaAlign.FLEX_END)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setWidth(72f)
        root_child0_child0.setHeight(72f)
        root_child0.addChildAt(root_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(52f, root.getLayoutWidth(), 0.0f)
        assertEquals(52f, root.getLayoutHeight(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutX(), 0.0f)
        assertEquals(-10f, root_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(72f, root_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_center_should_size_based_on_content() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignItems(YogaAlign.CENTER)
        root.setMargin(YogaEdge.TOP, 20f)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setJustifyContent(YogaJustify.CENTER)
        root_child0.setFlexShrink(1f)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setFlexGrow(1f)
        root_child0_child0.setFlexShrink(1f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child0_child0_child0 = createNode(config)
        root_child0_child0_child0.setWidth(20f)
        root_child0_child0_child0.setHeight(20f)
        root_child0_child0.addChildAt(root_child0_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(20f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(40f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(20f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(40f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_strech_should_size_based_on_parent() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setMargin(YogaEdge.TOP, 20f)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setJustifyContent(YogaJustify.CENTER)
        root_child0.setFlexShrink(1f)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setFlexGrow(1f)
        root_child0_child0.setFlexShrink(1f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child0_child0_child0 = createNode(config)
        root_child0_child0_child0.setWidth(20f)
        root_child0_child0_child0.setHeight(20f)
        root_child0_child0.addChildAt(root_child0_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(20f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(20f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(80f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_flex_start_with_shrinking_children() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setWidth(500f)
        root.setHeight(500f)
        val root_child0 = createNode(config)
        root_child0.setAlignItems(YogaAlign.FLEX_START)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setFlexGrow(1f)
        root_child0_child0.setFlexShrink(1f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child0_child0_child0 = createNode(config)
        root_child0_child0_child0.setFlexGrow(1f)
        root_child0_child0_child0.setFlexShrink(1f)
        root_child0_child0.addChildAt(root_child0_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(500f, root.getLayoutWidth(), 0.0f)
        assertEquals(500f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(500f, root.getLayoutWidth(), 0.0f)
        assertEquals(500f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(500f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_flex_start_with_stretching_children() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setWidth(500f)
        root.setHeight(500f)
        val root_child0 = createNode(config)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setFlexGrow(1f)
        root_child0_child0.setFlexShrink(1f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child0_child0_child0 = createNode(config)
        root_child0_child0_child0.setFlexGrow(1f)
        root_child0_child0_child0.setFlexShrink(1f)
        root_child0_child0.addChildAt(root_child0_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(500f, root.getLayoutWidth(), 0.0f)
        assertEquals(500f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(500f, root.getLayoutWidth(), 0.0f)
        assertEquals(500f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_flex_start_with_shrinking_children_with_stretch() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setWidth(500f)
        root.setHeight(500f)
        val root_child0 = createNode(config)
        root_child0.setAlignItems(YogaAlign.FLEX_START)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setFlexGrow(1f)
        root_child0_child0.setFlexShrink(1f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child0_child0_child0 = createNode(config)
        root_child0_child0_child0.setFlexGrow(1f)
        root_child0_child0_child0.setFlexShrink(1f)
        root_child0_child0.addChildAt(root_child0_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(500f, root.getLayoutWidth(), 0.0f)
        assertEquals(500f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(500f, root.getLayoutWidth(), 0.0f)
        assertEquals(500f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(500f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(500f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutY(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0_child0_child0.getLayoutHeight(), 0.0f)
    }

    private fun createNode(config: YogaConfig): YogaNode {
        return YogaNodeFactory.create(config)
    }
}
