/*
 * Copyright (C) 2023 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package app.cash.redwood.yoga

import app.cash.redwood.yoga.enums.YogaAlign
import app.cash.redwood.yoga.enums.YogaDirection
import app.cash.redwood.yoga.enums.YogaEdge
import app.cash.redwood.yoga.enums.YogaFlexDirection
import app.cash.redwood.yoga.enums.YogaWrap
import kotlin.test.Test
import kotlin.test.assertEquals

class YGAlignContentTest {
    @Test
    fun test_align_content_flex_start() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(130f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(10f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root_child2.setHeight(10f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(10f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root_child4.setHeight(10f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(130f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(10f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(10f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(20f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(130f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(80f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(30f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(80f, root_child2.getLayoutX(), 0.0f)
        assertEquals(10f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(30f, root_child3.getLayoutX(), 0.0f)
        assertEquals(10f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(80f, root_child4.getLayoutX(), 0.0f)
        assertEquals(20f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_flex_start_without_height_on_children() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(10f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(10f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(10f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(10f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(20f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(10f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(10f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(20f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_flex_start_with_flex() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(120f)
        val root_child0 = createNode(config)
        root_child0.setFlexGrow(1f)
        root_child0.setFlexBasisPercent(0f)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setFlexGrow(1f)
        root_child1.setFlexBasisPercent(0f)
        root_child1.setWidth(50f)
        root_child1.setHeight(10f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setFlexGrow(1f)
        root_child3.setFlexShrink(1f)
        root_child3.setFlexBasisPercent(0f)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(120f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(80f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(80f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(120f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(120f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(40f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(80f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(80f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(120f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_flex_end() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignContent(YogaAlign.FLEX_END)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(10f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root_child2.setHeight(10f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(10f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root_child4.setHeight(10f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(10f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(30f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(40f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(10f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(20f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(30f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(40f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(0f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(0f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_spacebetween() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.SPACE_BETWEEN)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(130f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(10f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root_child2.setHeight(10f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(10f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root_child4.setHeight(10f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(130f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(45f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(45f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(90f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(130f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(80f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(30f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(80f, root_child2.getLayoutX(), 0.0f)
        assertEquals(45f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(30f, root_child3.getLayoutX(), 0.0f)
        assertEquals(45f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(80f, root_child4.getLayoutX(), 0.0f)
        assertEquals(90f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_spacearound() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.SPACE_AROUND)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(140f)
        root.setHeight(120f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root_child0.setHeight(10f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(10f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root_child2.setHeight(10f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root_child3.setHeight(10f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root_child4.setHeight(10f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(140f, root.getLayoutWidth(), 0.0f)
        assertEquals(120f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(15f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(15f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(55f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(55f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(95f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(140f, root.getLayoutWidth(), 0.0f)
        assertEquals(120f, root.getLayoutHeight(), 0.0f)
        assertEquals(90f, root_child0.getLayoutX(), 0.0f)
        assertEquals(15f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(40f, root_child1.getLayoutX(), 0.0f)
        assertEquals(15f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(90f, root_child2.getLayoutX(), 0.0f)
        assertEquals(55f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(40f, root_child3.getLayoutX(), 0.0f)
        assertEquals(55f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(90f, root_child4.getLayoutX(), 0.0f)
        assertEquals(95f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_children() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setFlexGrow(1f)
        root_child0_child0.setFlexShrink(1f)
        root_child0_child0.setFlexBasisPercent(0f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_flex() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setFlexGrow(1f)
        root_child1.setFlexShrink(1f)
        root_child1.setFlexBasisPercent(0f)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setFlexGrow(1f)
        root_child3.setFlexShrink(1f)
        root_child3.setFlexBasisPercent(0f)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(0f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(0f, root_child3.getLayoutY(), 0.0f)
        assertEquals(0f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(0f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(0f, root_child3.getLayoutY(), 0.0f)
        assertEquals(0f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_flex_no_shrink() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setFlexGrow(1f)
        root_child1.setFlexShrink(1f)
        root_child1.setFlexBasisPercent(0f)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setFlexGrow(1f)
        root_child3.setFlexBasisPercent(0f)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(0f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(0f, root_child3.getLayoutY(), 0.0f)
        assertEquals(0f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(0f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(0f, root_child3.getLayoutY(), 0.0f)
        assertEquals(0f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_margin() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setMargin(YogaEdge.LEFT, 10f)
        root_child1.setMargin(YogaEdge.TOP, 10f)
        root_child1.setMargin(YogaEdge.RIGHT, 10f)
        root_child1.setMargin(YogaEdge.BOTTOM, 10f)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setMargin(YogaEdge.LEFT, 10f)
        root_child3.setMargin(YogaEdge.TOP, 10f)
        root_child3.setMargin(YogaEdge.RIGHT, 10f)
        root_child3.setMargin(YogaEdge.BOTTOM, 10f)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(60f, root_child1.getLayoutX(), 0.0f)
        assertEquals(10f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(40f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(60f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(80f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(40f, root_child1.getLayoutX(), 0.0f)
        assertEquals(10f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(40f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(40f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(40f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child4.getLayoutX(), 0.0f)
        assertEquals(80f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_padding() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setPadding(YogaEdge.LEFT, 10f)
        root_child1.setPadding(YogaEdge.TOP, 10f)
        root_child1.setPadding(YogaEdge.RIGHT, 10f)
        root_child1.setPadding(YogaEdge.BOTTOM, 10f)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setPadding(YogaEdge.LEFT, 10f)
        root_child3.setPadding(YogaEdge.TOP, 10f)
        root_child3.setPadding(YogaEdge.RIGHT, 10f)
        root_child3.setPadding(YogaEdge.BOTTOM, 10f)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_single_row() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root.addChildAt(root_child1, 1)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child1.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child1.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_fixed_height() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setHeight(60f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(80f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(80f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(80f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(80f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(80f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(60f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(80f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(80f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(80f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_max_height() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setMaxHeight(20f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(20f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(50f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(50f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_row_with_min_height() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setFlexDirection(YogaFlexDirection.ROW)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(150f)
        root.setHeight(100f)
        val root_child0 = createNode(config)
        root_child0.setWidth(50f)
        root.addChildAt(root_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setWidth(50f)
        root_child1.setMinHeight(80f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setWidth(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setWidth(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setWidth(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(90f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(90f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(90f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(90f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(90f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(150f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(90f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(0f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(90f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(0f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(90f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(100f, root_child3.getLayoutX(), 0.0f)
        assertEquals(90f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(90f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_column() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignContent(YogaAlign.STRETCH)
        root.setWrap(YogaWrap.WRAP)
        root.setWidth(100f)
        root.setHeight(150f)
        val root_child0 = createNode(config)
        root_child0.setHeight(50f)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setFlexGrow(1f)
        root_child0_child0.setFlexShrink(1f)
        root_child0_child0.setFlexBasisPercent(0f)
        root_child0.addChildAt(root_child0_child0, 0)
        val root_child1 = createNode(config)
        root_child1.setFlexGrow(1f)
        root_child1.setFlexShrink(1f)
        root_child1.setFlexBasisPercent(0f)
        root_child1.setHeight(50f)
        root.addChildAt(root_child1, 1)
        val root_child2 = createNode(config)
        root_child2.setHeight(50f)
        root.addChildAt(root_child2, 2)
        val root_child3 = createNode(config)
        root_child3.setHeight(50f)
        root.addChildAt(root_child3, 3)
        val root_child4 = createNode(config)
        root_child4.setHeight(50f)
        root.addChildAt(root_child4, 4)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(150f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child2.getLayoutX(), 0.0f)
        assertEquals(50f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child3.getLayoutX(), 0.0f)
        assertEquals(100f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(150f, root.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child0_child0.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child1.getLayoutX(), 0.0f)
        assertEquals(50f, root_child1.getLayoutY(), 0.0f)
        assertEquals(50f, root_child1.getLayoutWidth(), 0.0f)
        assertEquals(0f, root_child1.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child2.getLayoutX(), 0.0f)
        assertEquals(50f, root_child2.getLayoutY(), 0.0f)
        assertEquals(50f, root_child2.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child2.getLayoutHeight(), 0.0f)
        assertEquals(50f, root_child3.getLayoutX(), 0.0f)
        assertEquals(100f, root_child3.getLayoutY(), 0.0f)
        assertEquals(50f, root_child3.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child3.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child4.getLayoutX(), 0.0f)
        assertEquals(0f, root_child4.getLayoutY(), 0.0f)
        assertEquals(50f, root_child4.getLayoutWidth(), 0.0f)
        assertEquals(50f, root_child4.getLayoutHeight(), 0.0f)
    }

    @Test
    fun test_align_content_stretch_is_not_overriding_align_items() {
        val config = YogaConfigFactory.create()
        val root = createNode(config)
        root.setAlignContent(YogaAlign.STRETCH)
        val root_child0 = createNode(config)
        root_child0.setFlexDirection(YogaFlexDirection.ROW)
        root_child0.setAlignContent(YogaAlign.STRETCH)
        root_child0.setAlignItems(YogaAlign.CENTER)
        root_child0.setWidth(100f)
        root_child0.setHeight(100f)
        root.addChildAt(root_child0, 0)
        val root_child0_child0 = createNode(config)
        root_child0_child0.setAlignContent(YogaAlign.STRETCH)
        root_child0_child0.setWidth(10f)
        root_child0_child0.setHeight(10f)
        root_child0.addChildAt(root_child0_child0, 0)
        root.setDirection(YogaDirection.LTR)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(45f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutHeight(), 0.0f)
        root.setDirection(YogaDirection.RTL)
        root.calculateLayout(YogaConstants.UNDEFINED, YogaConstants.UNDEFINED)
        assertEquals(0f, root.getLayoutX(), 0.0f)
        assertEquals(0f, root.getLayoutY(), 0.0f)
        assertEquals(100f, root.getLayoutWidth(), 0.0f)
        assertEquals(100f, root.getLayoutHeight(), 0.0f)
        assertEquals(0f, root_child0.getLayoutX(), 0.0f)
        assertEquals(0f, root_child0.getLayoutY(), 0.0f)
        assertEquals(100f, root_child0.getLayoutWidth(), 0.0f)
        assertEquals(100f, root_child0.getLayoutHeight(), 0.0f)
        assertEquals(90f, root_child0_child0.getLayoutX(), 0.0f)
        assertEquals(45f, root_child0_child0.getLayoutY(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutWidth(), 0.0f)
        assertEquals(10f, root_child0_child0.getLayoutHeight(), 0.0f)
    }

    private fun createNode(config: YogaConfig): YogaNode {
        return YogaNodeFactory.create(config)
    }
}
