import static app.cash.redwood.buildsupport.TargetGroup.ToolkitHtml

redwoodBuild {
  targets(ToolkitHtml)
  publishing()
}

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        api projects.redwoodLayoutWidget
      }
    }
    commonMain {
      dependencies {
        api projects.redwoodLayoutSharedTest
        api projects.redwoodSnapshotTesting
      }
    }
  }
}
