import static app.cash.redwood.buildsupport.TargetGroup.Common

redwoodBuild {
  targets(Common)
  publishing()
}

apply plugin: 'app.cash.redwood.generator.testing'

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        api projects.redwoodUiLazylayoutCompose
        api projects.redwoodUiLazylayoutWidget
      }
    }
  }
}

redwoodSchema {
  source = projects.redwoodUiLazylayoutSchema
  type = 'app.cash.redwood.lazylayout.RedwoodLazyLayout'
}
