import static com.android.build.api.variant.DeviceTestBuilder.ANDROID_TEST_TYPE

apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

dependencies {
  implementation(libs.junit)
  implementation(libs.androidx.test.core)
  implementation(libs.androidx.test.uiautomator)
}

android {
  namespace = 'com.example.redwood.counter.android.tests'
}

androidComponents {
  beforeVariants(selector().all()) { variant ->
    variant.deviceTests.get(ANDROID_TEST_TYPE).enable = false
  }
}
